/**
 * Synthetic demo images so the verify flow can be shown end-to-end without the
 * user supplying files. Generates a mock "official circular" with a REAL,
 * scannable payment QR, plus variants:
 *   - a re-compressed copy               -> Verified Derivative
 *   - a copy whose payment QR was swapped -> Altered (payment tampering)
 */

import { Jimp } from "jimp";
import QRCode from "qrcode";
import { PDFDocument } from "pdf-lib";

const WIDTH = 480;
const HEIGHT = 320;

const APPROVED_UPI = "upi://pay?pa=sebi@valid&pn=SEBI&am=0";
const FRAUD_UPI = "upi://pay?pa=fraudster12@ybl&pn=SEBI%20Refund&am=5000";

function setPx(img: InstanceType<typeof Jimp>, x: number, y: number, rgb: [number, number, number]) {
  const w = img.bitmap.width;
  const i = (y * w + x) * 4;
  const d = img.bitmap.data;
  d[i] = rgb[0];
  d[i + 1] = rgb[1];
  d[i + 2] = rgb[2];
  d[i + 3] = 255;
}
function fillRect(img: InstanceType<typeof Jimp>, x0: number, y0: number, x1: number, y1: number, rgb: [number, number, number]) {
  for (let y = y0; y < y1; y++) for (let x = x0; x < x1; x++) setPx(img, x, y, rgb);
}

async function buildCircular(upiPayload: string): Promise<Buffer> {
  const img = new Jimp({ width: WIDTH, height: HEIGHT, color: 0xffffffff });
  fillRect(img, 0, 0, WIDTH, 56, [11, 37, 69]); // header band
  fillRect(img, 0, 56, WIDTH, 60, [200, 16, 46]); // accent rule
  for (let i = 0; i < 6; i++) {
    const y = 90 + i * 26;
    fillRect(img, 30, y, 30 + 260 - (i % 2) * 40, y + 10, [90, 107, 128]); // "text"
  }
  // Real scannable payment QR bottom-right.
  const qrPng = await QRCode.toBuffer(upiPayload, { width: 96, margin: 1 });
  const qr = await Jimp.read(qrPng);
  img.composite(qr, WIDTH - 116, HEIGHT - 116);
  return img.getBuffer("image/png");
}

async function recompress(pngBuffer: Buffer): Promise<Buffer> {
  const img = await Jimp.read(pngBuffer);
  return img.getBuffer("image/jpeg", { quality: 45 });
}

/** Wrap a circular PNG in a single-page PDF (forged SEBI circulars are PDFs). */
async function buildCircularPdf(upiPayload: string): Promise<Buffer> {
  const png = await buildCircular(upiPayload);
  const pdf = await PDFDocument.create();
  // Fixed metadata so the generated bytes are deterministic (a genuine copy
  // then byte-matches the signed record -> "original", not "derivative").
  const epoch = new Date(0);
  pdf.setCreationDate(epoch);
  pdf.setModificationDate(epoch);
  pdf.setProducer("PramaanSetu");
  pdf.setCreator("PramaanSetu");
  const page = pdf.addPage([WIDTH, HEIGHT]);
  const img = await pdf.embedPng(png);
  page.drawImage(img, { x: 0, y: 0, width: WIDTH, height: HEIGHT });
  return Buffer.from(await pdf.save());
}

/**
 * A deliberately "rendered-looking" image: smooth gradients, a soft blurred
 * subject, and no sensor noise. It is UNSIGNED, so verifying it exercises the
 * synthetic-media detector — the deterministic forensics flag the flat
 * compression residual and over-uniform noise typical of AI-generated imagery.
 * (For a live demo, uploading a real AI face render exercises the vision model
 * too; this built-in sample makes the forensic path demoable offline.)
 */
async function buildSyntheticLookingImage(): Promise<Buffer> {
  const w = 360;
  const h = 360;
  const img = new Jimp({ width: w, height: h, color: 0xffffffff });
  const d = img.bitmap.data;
  for (let y = 0; y < h; y++) {
    for (let x = 0; x < w; x++) {
      // Smooth radial + linear gradient, no high-frequency detail at all.
      const dx = (x - w / 2) / (w / 2);
      const dy = (y - h * 0.42) / (h / 2);
      const r = Math.sqrt(dx * dx + dy * dy);
      const glow = Math.max(0, 1 - r * 0.9);
      const i = (y * w + x) * 4;
      d[i] = Math.round(60 + 150 * glow + 30 * (x / w));
      d[i + 1] = Math.round(70 + 120 * glow + 20 * (y / h));
      d[i + 2] = Math.round(110 + 120 * glow);
      d[i + 3] = 255;
    }
  }
  // Lossless PNG: keeps the flat, noiseless surface intact so the forensic ELA
  // and noise-uniformity cues reflect the render itself, not JPEG artefacts.
  return img.getBuffer("image/png");
}

/**
 * A "camera-like" control: the same scene with realistic per-pixel sensor
 * noise, so the forensic detector reads it as natural (a useful contrast that
 * shows the detector does NOT just flag everything).
 */
async function buildAuthenticLookingImage(): Promise<Buffer> {
  const base = await Jimp.read(await buildSyntheticLookingImage());
  const d = base.bitmap.data;
  for (let i = 0; i < d.length; i += 4) {
    const n = (Math.random() - 0.5) * 70; // sensor-like noise
    d[i] = Math.max(0, Math.min(255, d[i] + n));
    d[i + 1] = Math.max(0, Math.min(255, d[i + 1] + n));
    d[i + 2] = Math.max(0, Math.min(255, d[i + 2] + n));
  }
  return base.getBuffer("image/png");
}

export interface DemoBundle {
  originalPng: Buffer;
  compressedJpg: Buffer; // -> Derivative
  alteredPng: Buffer; // -> Altered (swapped payment QR)
  originalPdf: Buffer; // signed reference PDF circular
  alteredPdf: Buffer; // -> Altered (forged PDF, swapped payment QR)
  syntheticSample: Buffer; // unsigned, AI-render-like -> synthetic detection
  authenticSample: Buffer; // unsigned, camera-like control
  approvedUpi: string;
  fraudUpi: string;
}

export async function makeDemoBundle(): Promise<DemoBundle> {
  const originalPng = await buildCircular(APPROVED_UPI);
  const compressedJpg = await recompress(originalPng);
  const alteredPng = await buildCircular(FRAUD_UPI);
  const originalPdf = await buildCircularPdf(APPROVED_UPI);
  const alteredPdf = await buildCircularPdf(FRAUD_UPI);
  const syntheticSample = await buildSyntheticLookingImage();
  const authenticSample = await buildAuthenticLookingImage();
  return {
    originalPng,
    compressedJpg,
    alteredPng,
    originalPdf,
    alteredPdf,
    syntheticSample,
    authenticSample,
    approvedUpi: "sebi@valid",
    fraudUpi: "fraudster12@ybl",
  };
}
